### ISSUE TITLE
Roadmap 2023 Q3

### ISSUE THREAD

**Issue by zuston** [zuston/legacy-riffle#1]
## Metrics

- [x] create the metric system structure
- [x] integrated with prometheus
- [ ] exposed more metrics about spill/stored/purged and so on

## Heartbeat to Coordinator
- [x] support dynamic memory info by heartbeat
- [x] support health check for different stores.

## Quick Recovery
- [ ] support quick recovery when restarting.

## Hybrid Store
- [x] support single buffer flush
- [ ] support retry flushing to localfile when meeting timeout
- [ ] allocated buffer release if not used

## Localfile Store
- [x] support multiple disk for localfile
- [x] support concurrency limit of writing for per disk
- [ ] support local order
- [ ] support global order
- [ ] read memory request

## Memory Store
- [x] support huge partition check and writing limit
- [ ] support block id filter when getting memory data

## HDFS Store
- [x] support HDFS
- [x] support kerberos
- [ ] support concurrent writing for one partition
