### ISSUE TITLE
Roadmap 2023H2

### ISSUE THREAD

**Issue by advancedxy** [zuston/legacy-riffle#21]
> ### Background

Discussed offline with @zuston, and we both agreed that it would be great to contribute this rust impl back to Apache Uniffle(Incubating)

> ### Goal and RoadMaps

#### 2023.09:
   * Goal: ready to contribute it back to Uniffle Repo
   * Results:
      * [x] Code refine:
         - [x] Rename datanode to shuffle worker
	 - [x] Build system:
	     - [x] Generate protobuf code programmatically
	     - [x] CI: style check, warning check, remove unused variable/imports
     - [x] Complete GRPC service support, including failure handling.
     - [x] Hdfs support refine
     - [x] Metrics/Logging refine
     * [x] New features:
       - [x]  Profiling tool support
       - [x]  Benchmark system
#### 2023.12:
- [ ] Included in the uniffle repo and finish integration test support
- [ ] Beta release in Uniffle's new release

**Comment by zuston** [comment]
Thanks for proposing this

**Comment by zuston** [comment]
How about naming the binary as the `uniffle-shuffle-worker` ? or `uniffle-worker` ? @advancedxy WDYT

**Comment by advancedxy** [comment]
Let's call it `uniffle-worker` then?

Uniffle itself already indicates shuffle.

**Comment by zuston** [comment]
> Let's call it `uniffle-worker` then?
> 
> Uniffle itself already indicates shuffle.

Let's do it.

**Comment by zuston** [comment]
I think all todos has been finished or on the progress. Do you have others? @advancedxy

**Comment by advancedxy** [comment]
> I think all todos has been finished or on the progress. Do you have others? @advancedxy

Currently no big features. However I have some todos in mind:
1. thread dump via http, it might be useful.
2. I haven't have a chance to run benchmark for myself, and maybe we can find some obvious improvements.
3. some small code refinements.. 

Anyway, I think we are on track. Maybe we can speed up and start migrating this repo to the uniffle repo by the end/middle of August.

**Comment by zuston** [comment]
> Anyway, I think we are on track. Maybe we can speed up and start migrating this repo to the uniffle repo by the end/middle of August.

`middle of August or earlier` will be better for me. After that, I will have not much time.

**Comment by advancedxy** [comment]
> > Anyway, I think we are on track. Maybe we can speed up and start migrating this repo to the uniffle repo by the end/middle of August.
> 
> `middle of August or earlier` will be better for me. After that, I will have not much time.

Let's start migrating next week then?

**Comment by zuston** [comment]
> > > Anyway, I think we are on track. Maybe we can speed up and start migrating this repo to the uniffle repo by the end/middle of August.
> > 
> > 
> > `middle of August or earlier` will be better for me. After that, I will have not much time.
> 
> Let's start migrating next week then?

Ok for me.
